# Use the official Python 3.6 image as the base image
FROM python:3.6

# Set the working directory inside the container
WORKDIR /finance

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Set the command to run when the container starts
CMD ["streamlit", "run", "app.py"]